import { IUsersOrder } from "store/usersOrders/usersOrders";

export const tempData: IUsersOrder[] = [
  {
    id: 12,
    tripDate: '2024-11-11 11:11',
    location: 'qwe',
    adultsAmount: 1,
    childrenUnder5: 0,
    childrenAbove5: 0,
    direction: 'fromAirport',
    isEnded: false,
    autoType: 'vito',
    airport: 'Анталья',
    users: [
      {
        id: 8,
        name: 'Фамилия Имя Отчество',
        arrivalDate: '2022-12-08 13:11',
        flightNumber: null,
        phoneNumber: '2131231',
        email: null,
        passport: '123',
        telegramLogin: '123123123',
        tripComment: 'Комментарий',
        identificationNumber: 1,
      },
      {
        id: 10,
        name: 'qqq',
        arrivalDate: ' ',
        flightNumber: null,
        phoneNumber: '',
        email: null,
        passport: '111',
        telegramLogin: '',
        tripComment: '',
        identificationNumber: 1,
      },
      {
        id: 11,
        name: 'qqq',
        arrivalDate: ' ',
        flightNumber: null,
        phoneNumber: '',
        email: null,
        passport: '111',
        telegramLogin: '',
        tripComment: '',
        identificationNumber: 1,
      },
      {
        id: 12,
        name: 'qqq',
        arrivalDate: ' ',
        flightNumber: null,
        phoneNumber: '',
        email: null,
        passport: '111',
        telegramLogin: '',
        tripComment: '',
        identificationNumber: 1,
      },
      {
        id: 13,
        name: 'qqq',
        arrivalDate: ' ',
        flightNumber: null,
        phoneNumber: '',
        email: null,
        passport: '111',
        telegramLogin: '',
        tripComment: '',
        identificationNumber: 1,
      },
      {
        id: 14,
        name: 'qqq',
        arrivalDate: ' ',
        flightNumber: null,
        phoneNumber: '',
        email: null,
        passport: '111',
        telegramLogin: '',
        tripComment: '',
        identificationNumber: 1,
      },
      {
        id: 15,
        name: 'qqq',
        arrivalDate: ' ',
        flightNumber: null,
        phoneNumber: '',
        email: null,
        passport: '111',
        telegramLogin: '',
        tripComment: '',
        identificationNumber: 1,
      },
    ],
  },
  {
    id: 6,
    tripDate: '2022-12-08 13:11',
    location: 'Москва',
    adultsAmount: 1,
    childrenUnder5: 0,
    childrenAbove5: 0,
    direction: 'fromAirport',
    isEnded: true,
    autoType: 'vito',
    airport: 'Анталья',
    users: [
      {
        id: 8,
        name: 'Фамилия Имя Отчество',
        arrivalDate: '2022-12-08 13:11',
        flightNumber: null,
        phoneNumber: '2131231',
        email: null,
        passport: '123',
        telegramLogin: '123123123',
        tripComment: 'Комментарий',
        identificationNumber: 1,
      },
      {
        id: 10,
        name: 'qqq',
        arrivalDate: ' ',
        flightNumber: null,
        phoneNumber: '',
        email: null,
        passport: '111',
        telegramLogin: '',
        tripComment: '',
        identificationNumber: 1,
      },
      {
        id: 11,
        name: 'qqq',
        arrivalDate: ' ',
        flightNumber: null,
        phoneNumber: '',
        email: null,
        passport: '111',
        telegramLogin: '',
        tripComment: '',
        identificationNumber: 1,
      },
      {
        id: 12,
        name: 'qqq',
        arrivalDate: ' ',
        flightNumber: null,
        phoneNumber: '',
        email: null,
        passport: '111',
        telegramLogin: '',
        tripComment: '',
        identificationNumber: 1,
      },
      {
        id: 13,
        name: 'qqq',
        arrivalDate: ' ',
        flightNumber: null,
        phoneNumber: '',
        email: null,
        passport: '111',
        telegramLogin: '',
        tripComment: '',
        identificationNumber: 1,
      },
      {
        id: 14,
        name: 'qqq',
        arrivalDate: ' ',
        flightNumber: null,
        phoneNumber: '',
        email: null,
        passport: '111',
        telegramLogin: '',
        tripComment: '',
        identificationNumber: 1,
      },
      {
        id: 15,
        name: 'qqq',
        arrivalDate: ' ',
        flightNumber: null,
        phoneNumber: '',
        email: null,
        passport: '111',
        telegramLogin: '',
        tripComment: '',
        identificationNumber: 1,
      },
    ],
  },
  {
    id: 10,
    tripDate: '2024-11-11 11:11',
    location: 'qwe',
    adultsAmount: 1,
    childrenUnder5: 0,
    childrenAbove5: 0,
    direction: 'fromAirport',
    isEnded: false,
    autoType: 'vito',
    airport: 'Анталья',
    users: [
      {
        id: 8,
        name: 'Фамилия Имя Отчество',
        arrivalDate: '2022-12-08 13:11',
        flightNumber: null,
        phoneNumber: '2131231',
        email: null,
        passport: '123',
        telegramLogin: '123123123',
        tripComment: 'Комментарий',
        identificationNumber: 1,
      },
      {
        id: 10,
        name: 'qqq',
        arrivalDate: ' ',
        flightNumber: null,
        phoneNumber: '',
        email: null,
        passport: '111',
        telegramLogin: '',
        tripComment: '',
        identificationNumber: 1,
      },
      {
        id: 11,
        name: 'qqq',
        arrivalDate: ' ',
        flightNumber: null,
        phoneNumber: '',
        email: null,
        passport: '111',
        telegramLogin: '',
        tripComment: '',
        identificationNumber: 1,
      },
      {
        id: 12,
        name: 'qqq',
        arrivalDate: ' ',
        flightNumber: null,
        phoneNumber: '',
        email: null,
        passport: '111',
        telegramLogin: '',
        tripComment: '',
        identificationNumber: 1,
      },
      {
        id: 13,
        name: 'qqq',
        arrivalDate: ' ',
        flightNumber: null,
        phoneNumber: '',
        email: null,
        passport: '111',
        telegramLogin: '',
        tripComment: '',
        identificationNumber: 1,
      },
      {
        id: 14,
        name: 'qqq',
        arrivalDate: ' ',
        flightNumber: null,
        phoneNumber: '',
        email: null,
        passport: '111',
        telegramLogin: '',
        tripComment: '',
        identificationNumber: 1,
      },
      {
        id: 15,
        name: 'qqq',
        arrivalDate: ' ',
        flightNumber: null,
        phoneNumber: '',
        email: null,
        passport: '111',
        telegramLogin: '',
        tripComment: '',
        identificationNumber: 1,
      },
    ],
  },
  {
    id: 9,
    tripDate: '2024-11-11 11:11',
    location: 'qwe',
    adultsAmount: 1,
    childrenUnder5: 0,
    childrenAbove5: 0,
    direction: 'fromAirport',
    isEnded: false,
    autoType: 'vito',
    airport: 'Анталья',
    users: [
      {
        id: 8,
        name: 'Фамилия Имя Отчество',
        arrivalDate: '2022-12-08 13:11',
        flightNumber: null,
        phoneNumber: '2131231',
        email: null,
        passport: '123',
        telegramLogin: '123123123',
        tripComment: 'Комментарий',
        identificationNumber: 1,
      },
      {
        id: 10,
        name: 'qqq',
        arrivalDate: ' ',
        flightNumber: null,
        phoneNumber: '',
        email: null,
        passport: '111',
        telegramLogin: '',
        tripComment: '',
        identificationNumber: 1,
      },
      {
        id: 11,
        name: 'qqq',
        arrivalDate: ' ',
        flightNumber: null,
        phoneNumber: '',
        email: null,
        passport: '111',
        telegramLogin: '',
        tripComment: '',
        identificationNumber: 1,
      },
      {
        id: 12,
        name: 'qqq',
        arrivalDate: ' ',
        flightNumber: null,
        phoneNumber: '',
        email: null,
        passport: '111',
        telegramLogin: '',
        tripComment: '',
        identificationNumber: 1,
      },
      {
        id: 13,
        name: 'qqq',
        arrivalDate: ' ',
        flightNumber: null,
        phoneNumber: '',
        email: null,
        passport: '111',
        telegramLogin: '',
        tripComment: '',
        identificationNumber: 1,
      },
      {
        id: 14,
        name: 'qqq',
        arrivalDate: ' ',
        flightNumber: null,
        phoneNumber: '',
        email: null,
        passport: '111',
        telegramLogin: '',
        tripComment: '',
        identificationNumber: 1,
      },
      {
        id: 15,
        name: 'qqq',
        arrivalDate: ' ',
        flightNumber: null,
        phoneNumber: '',
        email: null,
        passport: '111',
        telegramLogin: '',
        tripComment: '',
        identificationNumber: 1,
      },
    ],
  },
  {
    id: 11,
    tripDate: '2024-11-11 11:11',
    location: 'qwe',
    adultsAmount: 1,
    childrenUnder5: 0,
    childrenAbove5: 0,
    direction: 'fromAirport',
    isEnded: false,
    autoType: 'vito',
    airport: 'Анталья',
    users: [
      {
        id: 8,
        name: 'Фамилия Имя Отчество',
        arrivalDate: '2022-12-08 13:11',
        flightNumber: null,
        phoneNumber: '2131231',
        email: null,
        passport: '123',
        telegramLogin: '123123123',
        tripComment: 'Комментарий',
        identificationNumber: 1,
      },
      {
        id: 10,
        name: 'qqq',
        arrivalDate: ' ',
        flightNumber: null,
        phoneNumber: '',
        email: null,
        passport: '111',
        telegramLogin: '',
        tripComment: '',
        identificationNumber: 1,
      },
      {
        id: 11,
        name: 'qqq',
        arrivalDate: ' ',
        flightNumber: null,
        phoneNumber: '',
        email: null,
        passport: '111',
        telegramLogin: '',
        tripComment: '',
        identificationNumber: 1,
      },
      {
        id: 12,
        name: 'qqq',
        arrivalDate: ' ',
        flightNumber: null,
        phoneNumber: '',
        email: null,
        passport: '111',
        telegramLogin: '',
        tripComment: '',
        identificationNumber: 1,
      },
      {
        id: 13,
        name: 'qqq',
        arrivalDate: ' ',
        flightNumber: null,
        phoneNumber: '',
        email: null,
        passport: '111',
        telegramLogin: '',
        tripComment: '',
        identificationNumber: 1,
      },
      {
        id: 14,
        name: 'qqq',
        arrivalDate: ' ',
        flightNumber: null,
        phoneNumber: '',
        email: null,
        passport: '111',
        telegramLogin: '',
        tripComment: '',
        identificationNumber: 1,
      },
      {
        id: 15,
        name: 'qqq',
        arrivalDate: ' ',
        flightNumber: null,
        phoneNumber: '',
        email: null,
        passport: '111',
        telegramLogin: '',
        tripComment: '',
        identificationNumber: 1,
      },
    ],
  },
  {
    id: 13,
    tripDate: '2024-11-11 11:11',
    location: 'qwe',
    adultsAmount: 1,
    childrenUnder5: 0,
    childrenAbove5: 0,
    direction: 'fromAirport',
    isEnded: false,
    autoType: 'vito',
    airport: 'Анталья',
    users: [
      {
        id: 8,
        name: 'Фамилия Имя Отчество',
        arrivalDate: '2022-12-08 13:11',
        flightNumber: null,
        phoneNumber: '2131231',
        email: null,
        passport: '123',
        telegramLogin: '123123123',
        tripComment: 'Комментарий',
        identificationNumber: 1,
      },
      {
        id: 10,
        name: 'qqq',
        arrivalDate: ' ',
        flightNumber: null,
        phoneNumber: '',
        email: null,
        passport: '111',
        telegramLogin: '',
        tripComment: '',
        identificationNumber: 1,
      },
      {
        id: 11,
        name: 'qqq',
        arrivalDate: ' ',
        flightNumber: null,
        phoneNumber: '',
        email: null,
        passport: '111',
        telegramLogin: '',
        tripComment: '',
        identificationNumber: 1,
      },
      {
        id: 12,
        name: 'qqq',
        arrivalDate: ' ',
        flightNumber: null,
        phoneNumber: '',
        email: null,
        passport: '111',
        telegramLogin: '',
        tripComment: '',
        identificationNumber: 1,
      },
      {
        id: 13,
        name: 'qqq',
        arrivalDate: ' ',
        flightNumber: null,
        phoneNumber: '',
        email: null,
        passport: '111',
        telegramLogin: '',
        tripComment: '',
        identificationNumber: 1,
      },
      {
        id: 14,
        name: 'qqq',
        arrivalDate: ' ',
        flightNumber: null,
        phoneNumber: '',
        email: null,
        passport: '111',
        telegramLogin: '',
        tripComment: '',
        identificationNumber: 1,
      },
      {
        id: 15,
        name: 'qqq',
        arrivalDate: ' ',
        flightNumber: null,
        phoneNumber: '',
        email: null,
        passport: '111',
        telegramLogin: '',
        tripComment: '',
        identificationNumber: 1,
      },
    ],
  },
  {
    id: 8,
    tripDate: '2024-11-11 11:11',
    location: 'qwe',
    adultsAmount: 1,
    childrenUnder5: 0,
    childrenAbove5: 0,
    direction: 'fromAirport',
    isEnded: false,
    autoType: 'vito',
    airport: 'Анталья',
    users: [
      {
        id: 8,
        name: 'Фамилия Имя Отчество',
        arrivalDate: '2022-12-08 13:11',
        flightNumber: null,
        phoneNumber: '2131231',
        email: null,
        passport: '123',
        telegramLogin: '123123123',
        tripComment: 'Комментарий',
        identificationNumber: 1,
      },
      {
        id: 10,
        name: 'qqq',
        arrivalDate: ' ',
        flightNumber: null,
        phoneNumber: '',
        email: null,
        passport: '111',
        telegramLogin: '',
        tripComment: '',
        identificationNumber: 1,
      },
      {
        id: 11,
        name: 'qqq',
        arrivalDate: ' ',
        flightNumber: null,
        phoneNumber: '',
        email: null,
        passport: '111',
        telegramLogin: '',
        tripComment: '',
        identificationNumber: 1,
      },
      {
        id: 12,
        name: 'qqq',
        arrivalDate: ' ',
        flightNumber: null,
        phoneNumber: '',
        email: null,
        passport: '111',
        telegramLogin: '',
        tripComment: '',
        identificationNumber: 1,
      },
      {
        id: 13,
        name: 'qqq',
        arrivalDate: ' ',
        flightNumber: null,
        phoneNumber: '',
        email: null,
        passport: '111',
        telegramLogin: '',
        tripComment: '',
        identificationNumber: 1,
      },
      {
        id: 14,
        name: 'qqq',
        arrivalDate: ' ',
        flightNumber: null,
        phoneNumber: '',
        email: null,
        passport: '111',
        telegramLogin: '',
        tripComment: '',
        identificationNumber: 1,
      },
      {
        id: 15,
        name: 'qqq',
        arrivalDate: ' ',
        flightNumber: null,
        phoneNumber: '',
        email: null,
        passport: '111',
        telegramLogin: '',
        tripComment: '',
        identificationNumber: 1,
      },
    ],
  },
];
